language: node_js
node_js:
  - "14"
sudo: required
services: 
  - docker
before_install:
  - docker build -t cornelc/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true cornelc/docker-react npm run test
